/* Generated by Yosys 0.63 (git sha1 70a11c6bf, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module seq_detector_0011(clk, reset, data_in, detected);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input data_in;
  wire data_in;
  output detected;
  wire detected;
  wire _0_;
  reg [3:0] shift_register;
  assign _0_ = shift_register == 4'h3;
  always @(posedge clk, posedge reset)
    if (reset) shift_register <= 4'h0;
    else shift_register <= { shift_register[2:0], data_in };
  assign detected = _0_ ? 1'h1 : 1'h0;
endmodule
